### ISSUE TITLE
Chrome extension sidebar should close when a clipping is added.

### ISSUE THREAD

**Issue by Anthony-Fiddes** [Sherry2001/lobster-ice#38]
A confirmation message of some sort would also be cool.

**Comment by Sherry2001** [comment]
hey, it does right now. But yes, confirmation of some sort to come. May I close this?

**Comment by Sherry2001** [comment]
Yes! it should, once changes to server from the testing PR is merged to master. May i close this?

**Comment by Anthony-Fiddes** [comment]
Sure! I was just writing it on here so I wouldn't forget
